/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Visão;

/**
 *
 * @author WAZ-PC
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu6 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mainAluno = new javax.swing.JMenu();
        bntCadAluno = new javax.swing.JMenuItem();
        bntPesqAluno = new javax.swing.JMenuItem();
        mainFunc = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        bntPesqFunc = new javax.swing.JMenuItem();
        mainForn = new javax.swing.JMenu();
        bntCadForn = new javax.swing.JMenuItem();
        bntPesqForn = new javax.swing.JMenuItem();
        mainProd = new javax.swing.JMenu();
        bntCadProd = new javax.swing.JMenuItem();
        bntPesqProd = new javax.swing.JMenuItem();

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        jMenu6.setText("File");
        jMenuBar3.add(jMenu6);

        jMenu7.setText("Edit");
        jMenuBar3.add(jMenu7);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 0, 0));

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.black, null));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1076, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 612, Short.MAX_VALUE)
        );

        jLabel1.setText("jLabel1");

        jLabel2.setText("jLabel2");

        jMenuBar1.setBackground(new java.awt.Color(51, 0, 0));

        mainAluno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/1.png"))); // NOI18N
        mainAluno.setText("Aluno");

        bntCadAluno.setText("Cadatrar");
        mainAluno.add(bntCadAluno);

        bntPesqAluno.setText("Pesquisar");
        bntPesqAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntPesqAlunoActionPerformed(evt);
            }
        });
        mainAluno.add(bntPesqAluno);

        jMenuBar1.add(mainAluno);

        mainFunc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/2.png"))); // NOI18N
        mainFunc.setText("Funcionario");

        jMenuItem2.setText("Cadatrar");
        mainFunc.add(jMenuItem2);

        bntPesqFunc.setText("Pesquisar");
        bntPesqFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntPesqFuncActionPerformed(evt);
            }
        });
        mainFunc.add(bntPesqFunc);

        jMenuBar1.add(mainFunc);

        mainForn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/3.png"))); // NOI18N
        mainForn.setText("Fornecedor");

        bntCadForn.setText("Cadastrar");
        bntCadForn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntCadFornActionPerformed(evt);
            }
        });
        mainForn.add(bntCadForn);

        bntPesqForn.setText("Pesquisar");
        mainForn.add(bntPesqForn);

        jMenuBar1.add(mainForn);

        mainProd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/4.png"))); // NOI18N
        mainProd.setText("Produto");

        bntCadProd.setText("Cadastrar");
        mainProd.add(bntCadProd);

        bntPesqProd.setText("Pesquisar");
        mainProd.add(bntPesqProd);

        jMenuBar1.add(mainProd);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bntPesqFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntPesqFuncActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bntPesqFuncActionPerformed

    private void bntCadFornActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntCadFornActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bntCadFornActionPerformed

    private void bntPesqAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntPesqAlunoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bntPesqAlunoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem bntCadAluno;
    private javax.swing.JMenuItem bntCadForn;
    private javax.swing.JMenuItem bntCadProd;
    private javax.swing.JMenuItem bntPesqAluno;
    private javax.swing.JMenuItem bntPesqForn;
    private javax.swing.JMenuItem bntPesqFunc;
    private javax.swing.JMenuItem bntPesqProd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JMenu mainAluno;
    private javax.swing.JMenu mainForn;
    private javax.swing.JMenu mainFunc;
    private javax.swing.JMenu mainProd;
    // End of variables declaration//GEN-END:variables
}
